let menuList = {
    "body": {
        "operRoleMenuList": [{
                "bsnCode": "IM01",
                "bsnName": "系统管理",
                "type": "1",
                "url": "/sysmanage/branch/branchMain",
                "isOpen": "1",
                "isShow": "1",
                "warnMsg": "",
                "remark": "",
                "menuTreeOption": "",
                "menuTreeVerify": "",
                "parentBsnCode": "",
                "order": "0",
                "level": "1",
                "state": "1",
                "update": "",
                "bsnShort": "",
                "childrens": [{
                        "bsnCode": "IM0101",
                        "bsnName": "操作员管理",
                        "type": "1",
                        "url": "/sysmanage/operate/operateMain",
                        "isOpen": "1",
                        "isShow": "1",
                        "warnMsg": "",
                        "remark": "",
                        "menuTreeOption": "",
                        "menuTreeVerify": "",
                        "parentBsnCode": "IM01",
                        "order": "1",
                        "level": "2",
                        "state": "1",
                        "update": "",
                        "bsnShort": "",
                        "childrens": [],
                    },
                    {
                        "bsnCode": "IM0102",
                        "bsnName": "角色管理",
                        "type": "1",
                        "url": "/sysmanage/branch/branchMain1",
                        "isOpen": "1",
                        "isShow": "1",
                        "warnMsg": "",
                        "remark": "",
                        "menuTreeOption": "",
                        "menuTreeVerify": "",
                        "parentBsnCode": "IM01",
                        "order": "1",
                        "level": "2",
                        "state": "1",
                        "update": "",
                        "bsnShort": "",
                        "childrens": [],
                    }
                ]
            },
            {

                "bsnCode": "IM02",
                "bsnName": "服务控制",
                "type": "1",
                "url": "/sysmanage/branch/branchMain3",
                "isOpen": "1",
                "isShow": "1",
                "warnMsg": "",
                "remark": "",
                "menuTreeOption": "",
                "menuTreeVerify": "",
                "parentBsnCode": "",
                "order": "0",
                "level": "1",
                "state": "1",
                "update": "",
                "bsnShort": "",
                "childrens": [{
                    "bsnCode": "IM0201",
                    "bsnName": "应用参数",
                    "type": "1",
                    "url": "/sysmanage/branch/branchMain4",
                    "isOpen": "1",
                    "isShow": "1",
                    "warnMsg": "",
                    "remark": "",
                    "menuTreeOption": "",
                    "menuTreeVerify": "",
                    "parentBsnCode": "IM02",
                    "order": "1",
                    "level": "2",
                    "state": "1",
                    "update": "",
                    "bsnShort": "",
                    "childrens": [],
                }]
            },
            {

                "bsnCode": "IM03",
                "bsnName": "授权中心",
                "type": "1",
                "url": "/sysmanage/branch/branchMain5",
                "isOpen": "1",
                "isShow": "1",
                "warnMsg": "",
                "remark": "",
                "menuTreeOption": "",
                "menuTreeVerify": "",
                "parentBsnCode": "",
                "order": "0",
                "level": "1",
                "state": "1",
                "update": "",
                "bsnShort": "",
                "childrens": [{
                    "bsnCode": "IM0301",
                    "bsnName": "系统授权",
                    "type": "1",
                    "url": "/sysmanage/branch/branchMain6",
                    "isOpen": "1",
                    "isShow": "1",
                    "warnMsg": "",
                    "remark": "",
                    "menuTreeOption": "",
                    "menuTreeVerify": "",
                    "parentBsnCode": "IM03",
                    "order": "1",
                    "level": "2",
                    "state": "1",
                    "update": "",
                    "bsnShort": "",
                    "childrens": [],
                }]
            },
            {

                "bsnCode": "IM04",
                "bsnName": "限额管理",
                "type": "1",
                "url": "/sysmanage/branch/branchMain7",
                "isOpen": "1",
                "isShow": "1",
                "warnMsg": "",
                "remark": "",
                "menuTreeOption": "",
                "menuTreeVerify": "",
                "parentBsnCode": "",
                "order": "0",
                "level": "1",
                "state": "1",
                "update": "",
                "bsnShort": "",
                "childrens": [{
                    "bsnCode": "IM0401",
                    "bsnName": "账户管理",
                    "type": "1",
                    "url": "/sysmanage/branch/branchMain8",
                    "isOpen": "1",
                    "isShow": "1",
                    "warnMsg": "",
                    "remark": "",
                    "menuTreeOption": "",
                    "menuTreeVerify": "",
                    "parentBsnCode": "IM04",
                    "order": "1",
                    "level": "2",
                    "state": "1",
                    "update": "",
                    "bsnShort": "",
                    "childrens": [],
                }]
            },
            {

                "bsnCode": "IM05",
                "bsnName": "查询管理",
                "type": "1",
                "url": "/sysmanage/branch/branchMain9",
                "isOpen": "1",
                "isShow": "1",
                "warnMsg": "",
                "remark": "",
                "menuTreeOption": "",
                "menuTreeVerify": "",
                "parentBsnCode": "",
                "order": "0",
                "level": "1",
                "state": "1",
                "update": "",
                "bsnShort": "",
                "childrens": [{
                    "bsnCode": "IM0501",
                    "bsnName": "结算日查询",
                    "type": "1",
                    "url": "/sysmanage/branch/branchMain10",
                    "isOpen": "1",
                    "isShow": "1",
                    "warnMsg": "",
                    "remark": "",
                    "menuTreeOption": "",
                    "menuTreeVerify": "",
                    "parentBsnCode": "IM05",
                    "order": "1",
                    "level": "2",
                    "state": "1",
                    "update": "",
                    "bsnShort": "",
                    "childrens": [],
                }]
            },
            {
                "bsnCode": "IM06",
                "bsnName": "报表下载",
                "type": "1",
                "url": "/sysmanage/branch/branchMain11",
                "isOpen": "1",
                "isShow": "1",
                "warnMsg": "",
                "remark": "",
                "menuTreeOption": "",
                "menuTreeVerify": "",
                "parentBsnCode": "",
                "order": "0",
                "level": "1",
                "state": "1",
                "update": "",
                "bsnShort": "",
                "childrens": [{
                    "bsnCode": "IM0601",
                    "bsnName": "操作员日志",
                    "type": "1",
                    "url": "/sysmanage/branch/branchMain12",
                    "isOpen": "1",
                    "isShow": "1",
                    "warnMsg": "",
                    "remark": "",
                    "menuTreeOption": "",
                    "menuTreeVerify": "",
                    "parentBsnCode": "IM06",
                    "order": "1",
                    "level": "2",
                    "state": "1",
                    "update": "",
                    "bsnShort": "",
                    "childrens": [],
                }]
            }
        ]
    }
}
export default menuList